# Support Chatura Dissanayake's Creative Endeavors
github:
  - chaturawtf # Explore Chatura's open-source contributions
patreon:  # Become a patron of Chatura's design journey
open_collective:  # Support collaborative projects Chatura is involved in
ko_fi:  # Buy Chatura a coffee to fuel creativity
tidelift:  # Contribute to tools Chatura uses
community_bridge:  # Back initiatives Chatura cares about
liberapay:  # Support Chatura on a recurring basis
issuehunt:  # Fund issues Chatura solves
lfx_crowdfunding:  # Help crowdfund Chatura's projects
polar:  # Tip Chatura's work
buy_me_a_coffee: atakatus # Directly support Chatura's creative work
thanks_dev:  # Say thanks to Chatura for great code
custom: 
  - 'https://buymeacoffee.com/atakatus' # A direct way to support Chatura
  - 'https://github.com/sponsors/chaturawtf' # Sponsor Chatura on GitHub
